export const categories = [{name: "Career & Work", description: "How is your professional life, whether it may be a job, research, or school? Our professional side takes up more than we think."},
{name: "Money & Finances", description: "How are your financial circumstances?"},
{name: "Health & Fitness", description: "How are both your lifestyle and physical health? This includes aspects such as exercise, diet, and rest."},
{name: "Fun & Recreation", description: "Do you have enough opportunities to pursue your interests and hobbies outside of work?"},
{name: "Contribution", description: "How much are you donating? How do you respect the environment and the planet? Here, social causes are included."},
{name: "Community & Social", description: "How is your social life is going? How are your friends? Do you have positive, close friends with whom you can discuss anything?"},
{name: "Family & Friends", description: "How are your interactions with your family and friends?"},
{name: "Partner & Love", description: "If you are in a relationship, how is it? If you are single, how much love do you feel in your life? Being single does not necessarily mean a 0, and being with someone does not mean a 10."},
{name: "Personal Growth & Self-image", description: "How is your perception of yourself? This covers how you feel about yourself physically and how confident you are."},
{name: "Spirituality", description: "How is your relationship to the universe and your higher self? This is not necessarily related to being religious. How much do you connect with the spiritual side of life?"}]